### ISSUE TITLE
can't compile with ofx 0.8.3

### ISSUE THREAD

**Issue by batchku** [bakercp/IPCAM2SYPHON#2]
i'm using the 0.8.3 project generator to make a new app based on this example.
i'm using these addons:

![image](https://cloud.githubusercontent.com/assets/518356/3557336/855088b6-092e-11e4-884a-246ec3748d86.png)

here's the error i get with 'NSAutoreleasePool" during compilation:

![image](https://cloud.githubusercontent.com/assets/518356/3557345/94ccd5c4-092e-11e4-9305-11008b24081d.png)

**Comment by bakercp** [comment]
Are you compiling your program as objective-cpp by setting the source files be interpreted as that in the editor settings, or making sure their file suffixes are .mm?

**Comment by batchku** [comment]
A screen shot of where that setting is in Xcode

I think you have spotted te issue

**Comment by bakercp** [comment]
![otherviews_and_ofsketchapp__main_cpp_and_94ccd5c4-092e-11e4-9305-11008b24081d_png__16961228_](https://cloud.githubusercontent.com/assets/300484/3557622/c0c06198-0931-11e4-98e9-f17348dc6cff.png)

**Comment by bakercp** [comment]
Highlight the file you want to change, then go to the property inspector.

A better way (in my opinion) is just to change the main.cpp to main.mm.  It's more future proof as you will have to reset these file properties every time you make a new project file, whereas the .mm suffix is automatically compiled as obj-c++.

**Comment by batchku** [comment]
got it
now compiling it as objective c++ with main.mm suffix

here's where the compilation is getting stuck:

![image](https://cloud.githubusercontent.com/assets/518356/3557710/eb9f6ed0-0932-11e4-9354-6cc90369625b.png)

**Comment by bakercp** [comment]
Make sure you have Cocoa, OpenGL, IOKit and CoreVideo frameworks to the project as dependencies.

![ofsketchapp__main_cpp](https://cloud.githubusercontent.com/assets/300484/3557809/39578634-0934-11e4-9b56-31b12cb60793.png)

**Comment by bakercp** [comment]
Don't know why they wouldn't be there ... but if you are building from an old project file, they might not be.

**Comment by batchku** [comment]
all those frameworks are there already.

i'm now trying to compile your IPCAM2SYPHON app as it is, 
with its xcode project (instead of using the project generator)

i'm getting errors about syphon:

/Users/ali/Dropbox/Soft Dev/of_v0.8.3_osx_release/addons/ofxSyphon/src/ofxSyphonClient.mm:11:9: 'Syphon/Syphon.h' file not found

even though i have syphon installed :+1: 
![image](https://cloud.githubusercontent.com/assets/518356/3557840/95ea584a-0934-11e4-85e8-360c89f3c032.png)

**Comment by bakercp** [comment]
0.8.3 is no longer supported.  The development branch was recently updated for 0.9.3+.
